version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    AWS_ACCOUNT_ID: 636750014592
    REPO_NAME: rajsingh8826/react-frontend
    IMAGE_TAG: latest
    IMAGE_NAME: react-frontend

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ./frontend/ 
      - docker build -t $IMAGE_NAME .       
      - docker tag $IMAGE_NAME:latest $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
